# 10.5-常用内置对象-错误对象

## 一 tray/catch 语句

任何可能出错的代码都应该放到 try 块中，而处理错误的代码则放在 catch 块中，如下所示：

```js
try {
  throw 'foo'
} catch (e) {
  // ES2019 之后此处函数括号和参数可以省略
  console.log('An error happened!')
  console.log(e.message) // 可以向用户显示错误消息
}
```

如果 try 中的代码发生错误，则代码会立即退出执行，跳入 catch 中，并传入包含错误信息的对象，该对象的 message 属性在浏览器中的支持度最高。

try/catch 语句中有一个可选的 finally 子句，该子句无论是否发生错误都会最终运行。try 或 catch 块无法阻止 finally 块执行，包括 return 语句。

```js
function testFinally() {
  try {
    return 2
  } catch (error) {
    return 1
  } finally {
    return 0
  }
}
```

贴士：如果写出 finally 子句， catch 块就成了可选的（它们两者中只有一个是必需的）。只要代码中包含了 finally 子句， try 块或 catch 块中的 return 语句就会被忽略，上述示例中的 try 和 catch 的 return 数值并未获取到。

try/catch 语句最好用在自己无法控制的错误上。例如，假设你的代码中使用了一个大型 JavaScript 库的某个函数，而该函数可能会有意或由于出错而抛出错误。因为不能修改这个库的代码，所以为防止这个函数报告错误，就有必要通过 try/catch 语句把该函数调用包装起来，对可能的错误进行处理。

如果你明确知道自己的代码会发生某种错误，那么就不适合使用 try/catch 语句。例如，如果给函数传入字符串而不是数值时就会失败，就应该检查该函数的参数类型并采取相应的操作。这种情况下，没有必要使用 try/catch 语句。

## 二 错误类型

代码执行过程中会发生各种类型的错误，每种类型都会对应一个错误发生时抛出的错误对象。常见的错误对象有 8 种：

```txt
# 基本错误类型，其他错误类型继承该类型。
Error

# 继承自Error的具体错误类型
InternalError
EvalError
RangeError
ReferenceError
SyntaxError
TypeError
URIError
```

InternalError 类型的错误会在底层 JavaScript 引擎抛出异常时由浏览器抛出。例如，递归过多导致了栈溢出。这个类型并不是代码中通常要处理的错误，如果真发生了这种错误，很可能代码哪里弄错了或者有危险了。

RangeError 错误会在数值越界时抛出。例如，定义数组时如果设置了并不支持的长度，如-20 或 Number.MAX_VALUE，就会报告该错误：

```js
let items1 = new Array(-20) // 抛出 RangeError
let items2 = new Array(Number.MAX_VALUE) // 抛出 RangeError
```

ReferenceError 会在找不到对象时发生。（这就是著名的"object expected"浏览器错误的原因。）这种错误经常是由访问不存在的变量而导致的：

```js
let obj = x // 在 x 没有声明时会抛出 ReferenceError
```

TypeError 在 JavaScript 中很常见，主要发生在变量不是预期类型，或者访问不存在的方法时。很多原因可能导致这种错误，尤其是在使用类型特定的操作而变量类型不对时。

```js
let o = new 10() // 抛出 TypeError
console.log('name' in true) // 抛出 TypeError
Function.prototype.toString.call('name') // 抛出 TypeError
```

## 三 错误抛出

throw 用于抛出错误，该操作符必须有一个值：

```js
throw 12345
throw 'Hello world!'
throw true
throw { name: 'JavaScript' }
```

使用 throw 操作符时，代码立即停止执行，除非 try/catch 语句捕获了抛出的值。

可以通过内置的错误类型来模拟浏览器错误：

```js
throw new Error('Something bad happened.') // 可以是具体的错误类型
```

过继承 Error（第 6 章介绍过继承）也可以创建自定义的错误类型。创建自定义错误类型时，需要提供 name 属性和 message 属性，比如：

```js
class CustomError extends Error {
  constructor(message) {
    super(message)
    this.name = 'CustomError'
    this.message = message
  }
}
throw new CustomError('My message')
```

## 四 error 事件

任何没有被 try/catch 语句处理的错误都会在 window 对象上触发 error 事件。该事件是浏览器早期支持的事件，为保持向后兼容，很多浏览器保持了其格式不变。

```js
window.onerror = (message, url, line) => {
  console.log(message)
}
```

在任何错误发生时，无论是否是浏览器生成的，都会触发 error 事件并执行这个事件处理程序。然后，浏览器的默认行为就会生效，像往常一样显示这条错误消息。可以返回 false 来阻止浏览器默认报告错误的行为，如下所示：

```js
window.onerror = (message, url, line) => {
  console.log(message)
  return false
}
```

## 五 调试

### 5.1 控制台打印

常见的 consle 方法：

```txt
error(message)：在控制台中记录错误消息。
info(message)：在控制台中记录信息性内容。
log(message)：在控制台记录常规消息。
warn(message)：在控制台中记录警告消息
```

### 5.2 debugger 关键字

```js
function pauseExecution() {
  console.log('Will print before breakpoint')
  debugger
  console.log('Will not print until breakpoint continues')
}
```

在运行时碰到这个关键字时，所有主流浏览器都会打开开发者工具面板，并在指定位置显示断点。然后，可以通过单独的浏览器控制台在断点所在的特定词法作用域中执行代码。此外，还可以执行标准的代码调试器操作（单步进入、单步跳过、继续，等等）。

浏览器也支持在开发者工具的源代码标签页中选择希望设置断点的代码行来手动设置断点（不使用 debugger 关键字）。这样设置的断点与使用 debugger 关键字设置的一样，只是不会在不同浏览器会话之间保持。
